from enum import Enum
from typing import Dict, List, Tuple, Any
import numpy as np

class JagsError(Exception):
    """Exception raised by JAGS operations."""

    ...

class DumpType(Enum):
    """Flags for the function Console#dump_state"""

    DUMP_DATA: int
    DUMP_PARAMETERS: int
    DUMP_ALL: int

class FactoryType(Enum):
    """Enumerates factory types in a model"""

    SAMPLER_FACTORY: int
    MONITOR_FACTORY: int
    RNG_FACTORY: int

class Console:
    """Low-level wrapper around JAGS Console class."""

    def __init__(self) -> None: ...
    def checkModel(self, path: str) -> None:
        """Load the model from a file and checks its syntactic correctness."""
        ...

    def compile(self, data: Dict[str, Any], chains: int, generate_data: bool) -> None:
        """Compiles the model."""
        ...

    def setParameters(self, parameters: Dict[str, Any], chain: int) -> None:
        """Sets the parameters (unobserved variables) of the model."""
        ...

    def setRNGname(self, name: str, chain: int) -> None:
        """Sets the name of the RNG for the given chain."""
        ...

    def initialize(self) -> None:
        """Initializes the model."""
        ...

    def update(self, iterations: int) -> None:
        """Updates the Markov chain generated by the model."""
        ...

    def setMonitor(self, name: str, thin: int, type: str) -> None:
        """Sets a monitor for the given node array."""
        ...

    def setMonitors(self, names: List[str], thin: int, type: str) -> None:
        """Sets multiple monitors for the given node array."""
        ...

    def clearMonitor(self, name: str, type: str) -> None:
        """Clears a monitor."""
        ...

    def dumpState(self, type: DumpType, chain: int) -> Dict[str, Any]:
        """Dumps the state of the model."""
        ...

    def iter(self) -> int:
        """Returns the iteration number of the model."""
        ...

    def variableNames(self) -> List[str]:
        """Returns a vector of variable names used by the model."""
        ...

    def nchain(self) -> int:
        """Returns the number of chains in the model."""
        ...

    def dumpMonitors(self, type: str, flat: bool) -> Dict[str, np.ndarray]:
        """Dumps the contents of monitors."""
        ...

    def dumpSamplers(self) -> List[List[str]]:
        """Dumps the names of the samplers, and the corresponding sampled nodes vectors"""
        ...

    def adaptOff(self) -> None:
        """Turns off adaptive mode of the model."""
        ...

    def checkAdaptation(self) -> bool:
        """Checks whether adaptation is complete."""
        ...

    def isAdapting(self) -> bool:
        """Indicates whether model is in adaptive mode."""
        ...

    def clearModel(self) -> None:
        """Clears the model."""
        ...

    @staticmethod
    def loadModule(name: str) -> None:
        """Loads a module by name"""
        ...

    @staticmethod
    def unloadModule(name: str) -> None:
        """Unloads a module by name"""
        ...

    @staticmethod
    def listModules() -> List[str]:
        """Returns a list containing the names of loaded modules."""
        ...

    @staticmethod
    def listFactories(type: FactoryType) -> List[Tuple[str, bool]]:
        """Returns a list containing the names of currently loaded factories and whether or not they are active."""
        ...

    @staticmethod
    def setFactoryActive(name: str, type: FactoryType, active: bool) -> None:
        """Sets a factory to be active or inactive"""
        ...

    @staticmethod
    def na() -> float:
        """Return value of JAGS_NA."""
        ...

    @staticmethod
    def version() -> str:
        """Return version of JAGS library."""
        ...

    @staticmethod
    def parallel_rngs(factory: str, chains: int) -> List[Dict[str, Any]]:
        """RNGs for execution in parallel."""
        ...
